# Nixpacks configuration for Railway
# This file customizes the build process

[phases.setup]
nixPkgs = ["nodejs-20_x", "curl"]

[phases.install]
cmds = [
    "npm install --production=false"
]

[phases.build]
cmds = [
    "npm run build",
    "npm prune --production"
]

[start]
cmd = "npm run start:http"

[variables]
NODE_ENV = "production"