# Railway configuration
# This ensures the server starts in HTTP mode with health checks

[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:http:fixed"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3